### CRUD operations:
#### -Create
#### -Read
#### -Update
#### -Delete

## Create


In [2]:
import numpy as np 
matrix = np.arange(0, 25, 3).reshape((3, 3))
vector = np.random.randint(0, 25, size = 9)
scalar = np.random.randint(0, 25)


## Read

In [3]:
print("Матриця")
print(matrix)
print("Вектор")
print(vector)
print("Скаляр")
print(scalar)

Матриця
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
Вектор
[12  9 24  7  9 22  2 22 11]
Скаляр
10


## Update

In [5]:
print("Transpose matrix:")
print(matrix.transpose())
print("Vector plus 5:")
print(vector + 5)
print("Scalar devided by 3:")
print(scalar / 3)

Transpose matrix:
[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]
Vector plus 5:
[17 14 29 12 14 27  7 27 16]
Scalar devided by 3:
3.3333333333333335


## Delete


In [9]:
del matrix
matrix

NameError: name 'matrix' is not defined

In [10]:
del vecrot
vector

NameError: name 'vecrot' is not defined

In [11]:
del scalar
scalar

NameError: name 'scalar' is not defined