In [1]:
import numpy as np
data_set1 = np.arange(1,10)
data_set2 = np.random.randint(10, size = (3,3))
print("Завдання 1. NumPy")
print()
print("Набір даних, функція arrange:")
print(data_set1)
print("Набір даних, функція random:")
print(data_set2)
arr = np.save('data_set1.npy',data_set1)
output = np.load('data_set1.npy')
print("Зчитування з файлу:", output)
print()
print("Операції:скаляр, вектор, матриця")
print()
print ("Множення матриці на скаляр: ")
print (3*data_set2)
print ("Транспонування матриці: ")
print (np.transpose(data_set2))
numpy_array_1 = np.array([40, 50, 60])
numpy_array_2 = np.array([10, 20, 30])
print ("Сума двох векторів:")
print (np.add(numpy_array_1,numpy_array_2))
print ("Добуток векторів: ")
print (np.dot(numpy_array_1,numpy_array_2))
vector = np.arange(1,11)
print("Початковий вектор:")
print(data_set1)
vector_new = np.delete(data_set1,[1,2])
print("Видалення елементів:")
print(vector_new)

Завдання 1. NumPy

Набір даних, функція arrange:
[1 2 3 4 5 6 7 8 9]
Набір даних, функція random:
[[9 3 4]
 [8 9 7]
 [1 7 9]]
Зчитування з файлу: [1 2 3 4 5 6 7 8 9]

Операції:скаляр, вектор, матриця

Множення матриці на скаляр: 
[[27  9 12]
 [24 27 21]
 [ 3 21 27]]
Транспонування матриці: 
[[9 8 1]
 [3 9 7]
 [4 7 9]]
Сума двох векторів:
[50 70 90]
Добуток векторів: 
3200
Початковий вектор:
[1 2 3 4 5 6 7 8 9]
Видалення елементів:
[1 4 5 6 7 8 9]


### CRUD operations:
#### -Create
#### -Read
#### -Update
#### -Delete

## Create


In [2]:
import numpy as np 
matrix = np.arange(0, 25, 3).reshape((3, 3))
vector = np.random.randint(0, 25, size = 9)
scalar = np.random.randint(0, 25)


## Read

In [3]:
print("Матриця")
print(matrix)
print("Вектор")
print(vector)
print("Скаляр")
print(scalar)

Матриця
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
Вектор
[12  9 24  7  9 22  2 22 11]
Скаляр
10


## Update

In [5]:
print("Transpose matrix:")
print(matrix.transpose())
print("Vector plus 5:")
print(vector + 5)
print("Scalar devided by 3:")
print(scalar / 3)

Transpose matrix:
[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]
Vector plus 5:
[17 14 29 12 14 27  7 27 16]
Scalar devided by 3:
3.3333333333333335


## Delete


In [9]:
del matrix
matrix

NameError: name 'matrix' is not defined

In [10]:
del vecrot
vector

NameError: name 'vecrot' is not defined

In [11]:
del scalar
scalar

NameError: name 'scalar' is not defined